### PR TITLE
improving spring usage

### PR DESCRIPTION
**Pull request by FabiKo117**
starting with adding more spring functionalities
using bean components to apply auto-injection in different classes

### CODE REVIEW

**Comment by FabiKo117** [comment]
This PR is quite outdated by now, but still I guess it would make sense to grab it up again at some point and continue the started work. As it's more a structural change, it could also wait until after our review I guess.

**Comment by bonaparten** [comment]
> This PR is quite outdated by now, but still I guess it would make sense to grab it up again at some point and continue the started work. As it's more a structural change, it could also wait until after our review I guess.

I was thinking the same. You are right. After the review, we should work on it.

**Comment by FabiKo117** [comment]
> I was thinking the same. You are right. After the review, we should work on it.
> Can we close [#53](https://github.com/GIScience/ohsome-api/pull/53) or should it stay still open?
@bonaparten It should stay open, as there has most likely not everything been considered and transfered over to this new branch and PR. Is not a nice situation, but as there's a lot of code and work involved, I'd prefer to keep it to not lose the achieved progress and thoughts.

**Comment by tyrasd** [comment]
closing stale branch

**Pull request closed without merging**
