### PR TITLE
make sure groupByEntity is called before filters are set

### PR DESCRIPTION
**Pull request by tyrasd**
fixes a bug in the implementation of the oshdb upgrade (to version 0.6) in #86

### CODE REVIEW

**Review by joker234 — APPROVED** [review]
Resolves the addressed bug. Checked with check-ohsome-api and ohsome-api-outputcomparer.
@FabiKo117, do you want to have a look too?

**Comment by FabiKo117** [comment]
> Resolves the addressed bug. Checked with check-ohsome-api and ohsome-api-outputcomparer.
> @FabiKo117, do you want to have a look too?

I was following your discussions and it seems like you resolved it, so I don't have to.
We should continue to discuss though how we can avoid that in future releases.

**Comment by FabiKo117** [comment]
I can run the affected data-extraction tests then once I've updated them for https://github.com/GIScience/ohsome-api/pull/100.

**Review by FabiKo117 — APPROVED** [review]
Tested with updated tests from https://github.com/GIScience/ohsome-api/pull/100 and it works 👍

**Pull request merged**
