### PR TITLE
Jenkinsfile minor fix and clean up

### PR DESCRIPTION
**Pull request by joker234**
### Description
fixes a small issue with rocketchat messages issued by Jenkins

### Corresponding issue
None

### New or changed dependencies
None

### Checklist
- ~[ ] My code follows the [code-style](https://github.com/GIScience/ohsome-api/blob/master/CONTRIBUTING.md#code-style) rules, and I have checked on the [static analyses](https://jenkins.ohsome.org/job/ohsome-api/view/change-requests/)~
- ~[ ] I have commented my code~
- ~[ ] I have written javadoc (required for public methods)~
- ~[ ] I have added sufficient unit and API tests~
- ~[ ] I have made corresponding changes to the [documentation](https://github.com/GIScience/ohsome-api/tree/master/docs)~
- ~[ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-api/blob/master/CHANGELOG.md)~
- ~[ ] I have adjusted the examples in the [check-ohsome-api](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/check-ohsome-api) script or [created an issue](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/helpers/check-ohsome-api/-/issues/new) in the corresponding repository. More Information [here](https://github.com/GIScience/ohsome-api/blob/master/CONTRIBUTING.md#check-examples).~

Please check all finished tasks. If some tasks do not apply to your PR, please cross their text out (by using `~...~`) and remove their checkboxes.

### CODE REVIEW

**Comment by FabiKo117** [comment]
What is the effect of the `trim()` function here?

**Comment by joker234** [comment]
> What is the effect of the `trim()` function here?

In most programming languages (I know) `trim` “trims” the string. That means it removes all unnecessary whitespaces, newlines, … at the beginning and end of the string. That's what it's supposed to do in this case, as you can see in the lines below the changed lines.

**Comment by joker234** [comment]
P.S.: I added this change to all Repos managed in Jenkins :)

**Review by tyrasd — APPROVED** [review]
looks good. the only difference to https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/libs/changeset-metadata/-/blob/9f779721ba10d0a983a4f92df15ac626156ae497/Jenkinsfile which is not marked as _ohsome-api_ specific is line 214 (https://github.com/GIScience/ohsome-api/pull/128/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8R214)

**Pull request merged**
